# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 03:49
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 28, 3, 49, 56, 850901))),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('description', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suryaSoftApp.User'),
        ),
    ]
