# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaSoftApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
