# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaSoftApp', '0002_auto_20190328_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
