# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suryaSoftApp', '0003_user_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='aaaa', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='aaaa', max_length=50),
        ),
    ]
